//! **The differential oracle for the manifest `get_batch` — same discipline as the page one.**
//!
//! A batched manifest fetch must return **byte-identical** manifests to N serial `get`s for any set of
//! ids, and be **all-or-nothing** (a missing or corrupt manifest fails the whole batch, never a partial
//! set as success). A corrupt manifest is a corrupt view of the *entire* database, so this is the last
//! place a torn batch may masquerade as a complete one.
//!
//! Manifests are generated by a real `Pager` chain (each commit is a distinct manifest, overlays and
//! all), seeded straight into a remote, then fetched by a cold `TieredManifestStore`.

use object_store::memory::InMemory;
use object_store::ObjectStore;
use std::sync::Arc;
use substrate_pager::{
    Manifest, ManifestId, ManifestStore, MemCas, MemManifestStore, PageHasher, PageStore, Pager,
    PagerError, StoreConfig, MIN_PAGE_SIZE,
};
use substrate_store::{RemoteTier, TieredManifestStore};

const N_SEED: usize = 40;

struct Rng(u64);
impl Rng {
    fn next(&mut self) -> u64 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        self.0
    }
    fn below(&mut self, n: usize) -> usize {
        if n == 0 {
            0
        } else {
            (self.next() % n as u64) as usize
        }
    }
}

/// Generate `N_SEED` distinct manifests via a real Pager chain, and return (ids, manifests) aligned.
fn make_manifests() -> (Vec<ManifestId>, Vec<Manifest>) {
    let config = StoreConfig {
        page_size: MIN_PAGE_SIZE,
        pool: "gen".into(),
        ..Default::default()
    };
    let cas = Arc::new(MemCas::new(PageHasher::Unkeyed));
    let local: Arc<dyn ManifestStore> = Arc::new(MemManifestStore::new());
    let pager = Pager::from_parts(cas, Arc::clone(&local), config).expect("pager");

    let mut ids = Vec::with_capacity(N_SEED);
    for k in 0..N_SEED {
        let mut txn = pager.begin().expect("begin");
        pager
            .write(&mut txn, 0, format!("commit-{k}-distinct").into_bytes())
            .expect("write");
        ids.push(pager.commit(txn).expect("commit"));
    }
    let manifests = ids
        .iter()
        .map(|&id| local.get(id).expect("local manifest"))
        .collect();
    (ids, manifests)
}

async fn seed(remote: &RemoteTier, ids: &[ManifestId], manifests: &[Manifest]) {
    for (id, m) in ids.iter().zip(manifests) {
        remote
            .put(&remote.manifest_key(*id), m.encode().expect("encode"))
            .await
            .expect("seed put");
    }
}

fn cold_tier(remote: &RemoteTier) -> Arc<TieredManifestStore> {
    TieredManifestStore::new(Arc::new(MemManifestStore::new()), remote.clone()).expect("tier")
}

#[tokio::test(flavor = "multi_thread")]
async fn manifest_get_batch_is_byte_identical_to_n_serial_gets_for_any_set() {
    let (ids, manifests) = make_manifests();
    let remote = RemoteTier::new(Arc::new(InMemory::new()), "oracle");
    seed(&remote, &ids, &manifests).await;

    let mut rng = Rng(0x0FA17E5);
    for case in 0..300u64 {
        let len = rng.below(2 * N_SEED + 1);
        let set_idx: Vec<usize> = (0..len).map(|_| rng.below(N_SEED)).collect();
        let set: Vec<ManifestId> = set_idx.iter().map(|&i| ids[i]).collect();

        // Serial reference on a fresh cold tier.
        let serial_tier = cold_tier(&remote);
        let serial: Vec<Manifest> = set
            .iter()
            .map(|&id| serial_tier.get(id).expect("serial get"))
            .collect();

        // Batched, independent fresh cold tier.
        let batch_tier = cold_tier(&remote);
        let batch = batch_tier.get_batch(&set).expect("get_batch");

        assert_eq!(batch.len(), set.len(), "case {case}: wrong count");
        for (j, &idx) in set_idx.iter().enumerate() {
            // Ground truth: the seed manifest's bytes.
            assert_eq!(
                batch[j].encode().unwrap(),
                manifests[idx].encode().unwrap(),
                "case {case} pos {j}: batch manifest != seed truth"
            );
            assert_eq!(
                batch[j].encode().unwrap(),
                serial[j].encode().unwrap(),
                "case {case} pos {j}: batch != N serial gets"
            );
        }
    }
}

#[tokio::test(flavor = "multi_thread")]
async fn a_missing_manifest_fails_the_whole_batch() {
    let (ids, manifests) = make_manifests();
    let remote = RemoteTier::new(Arc::new(InMemory::new()), "oracle");
    seed(&remote, &ids, &manifests).await;

    // A manifest id that was never seeded (a fresh Pager chain the remote never saw).
    let (ghost_ids, _) = make_manifests_seeded_elsewhere();
    let ghost = ghost_ids[0];

    let tier = cold_tier(&remote);
    let set = vec![ids[0], ids[1], ghost, ids[2]];
    match tier.get_batch(&set) {
        Err(PagerError::MissingManifest(_)) => {}
        other => panic!("a missing manifest must fail the whole batch, got {other:?}"),
    }
}

#[tokio::test(flavor = "multi_thread")]
async fn a_corrupt_manifest_fails_the_whole_batch() {
    let (ids, manifests) = make_manifests();
    let backend = Arc::new(InMemory::new());
    let remote = RemoteTier::new(backend.clone(), "oracle");
    seed(&remote, &ids, &manifests).await;

    // Overwrite ids[1]'s object with bytes that do not hash to it — straight through the raw backend
    // (RemoteTier::put is idempotent-skip). Any invalid encoding fails decode; wrong-but-valid fails the
    // id check. Use another manifest's bytes: valid encoding, wrong id.
    let other_bytes = manifests[2].encode().unwrap();
    backend
        .put(&remote.manifest_key(ids[1]), other_bytes.into())
        .await
        .expect("tamper");

    let tier = cold_tier(&remote);
    match tier.get_batch(&[ids[0], ids[1]]) {
        Err(PagerError::MissingManifest(_)) => {}
        other => {
            panic!("a manifest whose bytes hash to another id must fail the batch, got {other:?}")
        }
    }
}

/// A second, independent Pager chain — its manifest ids exist nowhere in the first remote.
fn make_manifests_seeded_elsewhere() -> (Vec<ManifestId>, Vec<Manifest>) {
    let config = StoreConfig {
        page_size: MIN_PAGE_SIZE,
        pool: "elsewhere".into(),
        ..Default::default()
    };
    let cas = Arc::new(MemCas::new(PageHasher::Unkeyed));
    let local: Arc<dyn ManifestStore> = Arc::new(MemManifestStore::new());
    let pager = Pager::from_parts(cas, Arc::clone(&local), config).expect("pager");
    let mut ids = Vec::new();
    for k in 0..4 {
        let mut txn = pager.begin().expect("begin");
        pager
            .write(&mut txn, 0, format!("ELSEWHERE-{k}").into_bytes())
            .expect("write");
        ids.push(pager.commit(txn).expect("commit"));
    }
    let manifests = ids.iter().map(|&id| local.get(id).expect("m")).collect();
    (ids, manifests)
}
